### ISSUE TITLE
Implement thumbnail generation to `File.save`

### ISSUE THREAD

**Issue by fugal-dy** [projectcaluma/alexandria#454]
Thumbnail generation should be configured in setting `ALEXANDRIA_ENABLE_THUMBNAIL_GENERATION` and be applied regardless.

The thumbnail creation logic of `FileViewSet`.`create` should be moved to the `File`.`save` method to maintain consistency.

https://github.com/projectcaluma/alexandria/blob/48e55828bab60cd7bd0820f5f6a32e8dc375e276/alexandria/core/views.py#L194-L214

**Comment by Yelinz** [comment]
solved by https://github.com/projectcaluma/alexandria/pull/513
